# INSERT INTO `authors` (`firstname`, `lastname`, `age`) VALUES ('Leiner', 'Laura', 36);
# INSERT INTO `authors` (`firstname`, `lastname`, `age`) VALUES ('Sara', 'Shepard', 44);
# INSERT INTO `authors` (`firstname`, `lastname`, `age`) VALUES ('Cecily von', 'Ziegesar', 51);
# INSERT INTO `authors` (`firstname`, `lastname`, `age`) VALUES ('Stephenie', 'Meyer', 47);
# INSERT INTO `authors` (`firstname`, `lastname`, `age`) VALUES ('Anna', 'Todd', 32);
# INSERT INTO `books` (`title`, `release_date`, `id_author`) VALUES ('Twilight', '2005', (SELECT id FROM authors WHERE firstname = 'Stephenie' AND lastname = 'Meyer'));
# INSERT INTO `books` (`title`, `release_date`, `id_author`) VALUES ('New Moon', '2006', (SELECT id FROM authors WHERE firstname = 'Stephenie' AND lastname = 'Meyer'));
# INSERT INTO `books` (`title`, `release_date`, `id_author`) VALUES ('Eclipse', '2007', (SELECT id FROM authors WHERE firstname = 'Stephenie' AND lastname = 'Meyer'));
# INSERT INTO `books` (`title`, `release_date`, `id_author`) VALUES ('Breaking Dawn', '2008', (SELECT id FROM authors WHERE firstname = 'Stephenie' AND lastname = 'Meyer'));
# INSERT INTO `books` (`title`, `release_date`, `id_author`) VALUES ('I Like It Like That', '2004', (SELECT id FROM authors WHERE firstname = 'Cecily von' AND lastname = 'Ziegesar'));
# INSERT INTO `books` (`title`, `release_date`, `id_author`) VALUES ('Because I\'m Worth It', '2003', (SELECT id FROM authors WHERE firstname = 'Cecily von' AND lastname = 'Ziegesar'));
# INSERT INTO `books` (`title`, `release_date`, `id_author`) VALUES ('Pretty Little Liars', '2012', (SELECT id FROM authors WHERE firstname = 'Sara' AND lastname = 'Shepard'));
# INSERT INTO `books` (`title`, `release_date`, `id_author`) VALUES ('Szent Johanna Gimi', '2013', (SELECT id FROM authors WHERE firstname = 'Leiner' AND lastname = 'Laura'));
# INSERT INTO `books` (`title`, `release_date`, `id_author`) VALUES ('Mindig Karácsony', '2019', (SELECT id FROM authors WHERE firstname = 'Leiner' AND lastname = 'Laura'));
# INSERT INTO `books` (`title`, `release_date`, `id_author`) VALUES ('Higgy nekem', '2021', (SELECT id FROM authors WHERE firstname = 'Leiner' AND lastname = 'Laura'));
# INSERT INTO `books` (`title`, `release_date`, `id_author`) VALUES ('After', '2014', (SELECT id FROM authors WHERE firstname = 'Anna' AND lastname = 'Todd'));
# INSERT INTO `books` (`title`, `release_date`, `id_author`) VALUES ('After We Collided', '2014',  (SELECT id FROM authors WHERE firstname = 'Anna' AND lastname = 'Todd'));
# INSERT INTO `books` (`title`, `release_date`, `id_author`) VALUES ('After We Fell', '2014', (SELECT id FROM authors WHERE firstname = 'Anna' AND lastname = 'Todd'));
# INSERT INTO `books` (`title`, `release_date`, `id_author`) VALUES ('After Ever Happy', '2015', (SELECT id FROM authors WHERE firstname = 'Anna' AND lastname = 'Todd'));
